# Generated by Django 3.1 on 2022-07-28 11:41

import common.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='css',
            field=models.FileField(blank=True, upload_to=common.common.file_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='html',
            field=models.FileField(blank=True, upload_to=common.common.file_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='js',
            field=models.FileField(blank=True, upload_to=common.common.file_upload_path),
        ),
    ]
