version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/interactive-web-server/ # test
   
permissions:
  - object: /home/ec2-user/deploy
    pattern: "**"
    owner: ec2-user
    group: ec2-user
   
hooks:
  BeforeInstall:
    - location: scripts/remove_server.sh 
      timeout: 300 
      runas: root 
  Install: 
    - location: scripts/install_dependencies.sh
      runas: root 
  ApplicationStart: 
    - location: scripts/start_server.sh
      runas: root



