version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencyrpt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done; '"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    build: .
    command: gunicorn web_editor.web_editor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: mysql
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: editor_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: web_editor_db
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_secret

secrets:
  mysql_secret:
    file: mysql_secret

volumes:
  mysql_data:
