version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      #- ./certbot/conf:/etc/letsencrypt
      #- ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web


  #certbot:
  #  image: certbot/certbot
  #  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done; '"
  #  volumes:
  #    - ./certbot/conf:/etc/letsencrypt
  #    - ./certbot/www:/var/www/certbot

  asgi:
    build:
      context: ./web_editor
      dockerfile: web_editor.Dockerfile
    command: gunicorn web_editor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web_editor:/usr/src/app/
    ports:
      - 8001:8001
    links:
      - redis
    expose:
      - 8001
  
  wsgi:
    build:
      context: ./web_editor
      dockerfile: web_editor.Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 web_editor.asgi:application
    volumes:
      - ./web_editor:/usr/src/app/
    ports:
      - 8000:8000
    links:
      - redis
    expose:
      - 8000

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    