version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      #- ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80 # 81:80
      - 443:443 # 444:443
    depends_on:
      - web
  #certbot:
    #image: certbot/certbot
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done; '"
    #volumes:
     # - ./data/certbot/conf:/etc/letsencrypt
     # - ./data/certbot/www:/var/www/certbot
  web:
    build:
      context: ./web_editor
      dockerfile: web_editor.Dockerfile
    #command: gunicorn web_editor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web_editor:/usr/src/app/
    ports:
      8000:8000
    #depends_on:
    #  - db
  #db:
    #image: mysql
    #build:
      #context: ./mysql
      #dockerfile: ./mysql.Dockerfile
    #ports:
     # - 3308:3306
    #environment:
      #MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      #MYSQL_USER: editor_db_user
      #MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      #MYSQL_DATABASE: web_editor_db
    #volumes:
     # - mysql_data:/var/lib/mysql
    #secrets:
     # - mysql_secret
    #deploy:
     # resources:
     #   limits:
     #     memory: 50M
     #   reservations:
     #     memory: 20M


#secrets:
 # mysql_secret:
  #  file: ../mysql_secret

#volumes:
 # mysql_data:
