version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencyrpt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/bash -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done; '"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    build: .
    command: gunicorn web_editor.web_editor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
