version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      #- ./certbot/conf:/etc/letsencrypt
      #- ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  #certbot:
  #  image: certbot/certbot
  #  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done; '"
  #  volumes:
  #    - ./certbot/conf:/etc/letsencrypt
  #    - ./certbot/www:/var/www/certbot

  web:
    build:
      context: ./web_editor
      dockerfile: web_editor.Dockerfile
    #command: gunicorn web_editor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web_editor:/usr/src/app/
    ports:
      - 8000:8000
