# Generated by Django 3.1 on 2022-05-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=100)),
                ('tag', models.JSONField(default=dict)),
                ('visibility', models.BooleanField(default=True)),
                ('z_index', models.IntegerField()),
                ('svg_type', models.CharField(choices=[('RE', 'Rectangle'), ('EL', 'Ellipse'), ('PA', 'Path'), ('DR', 'Drawing'), ('IM', 'Image'), ('TE', 'Text')], max_length=2)),
                ('fill', models.CharField(max_length=30)),
                ('stroke', models.CharField(max_length=30)),
                ('d_string', models.CharField(max_length=500)),
                ('src_url', models.URLField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
