# Generated by Django 3.2 on 2022-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='d_string',
        ),
        migrations.RemoveField(
            model_name='object',
            name='fill',
        ),
        migrations.RemoveField(
            model_name='object',
            name='stroke',
        ),
        migrations.RemoveField(
            model_name='object',
            name='svg_type',
        ),
        migrations.AddField(
            model_name='object',
            name='object_name',
            field=models.CharField(default='sample', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='opacity',
            field=models.FloatField(default=1.0),
        ),
    ]
