# Generated by Django 3.2 on 2022-11-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_auto_20221112_1846'),
        ('object', '0002_object_project'),
    ]

    operations = [
    ]
