# Generated by Django 3.2 on 2022-11-19 13:26

import common.common
from django.db import migrations, models
import web_editor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_merge_0002_auto_20221112_1846_0002_object_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.FileField(blank=True, storage=web_editor.storage_backends.MediaStorage(), upload_to=common.common.file_upload_path),
        ),
    ]
