name: Deploy

on:
  #workflow_run:
    #workflows: [Test CI]
    #branches: 
      #- main
    #types:
      #- completed
  push:
    branches:
      - main

jobs:
  continuous-deployment:
    name: Deploy
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      IMAGE_TAG: ${{ github.run_number }}
      BUILD_NUMBER: ${{ github.run_number }}
      ECR_REGISTRY: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com
      ECR_REPOSITORY: webgam-dev/webgam-server

    steps:
      # Step 1
      - name: Checkout
        uses: actions/checkout@v2 

      # Step 2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Step 3
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4
      - name: Docker Build, tag, and push image to ECR
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
