name: Django CD

on:
  #workflow_run:
    #workflows: [Django CI]
    #branches: 
      #- main
    #types:
      #- completed
  push: 
    branches:
      - main
      - websocket_project

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      # Step 1
      - name: Checkout
        uses: actions/checkout@v2 
        
      # Step 2    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Step 3
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name webgam-deploy \
          --deployment-group-name webgam-dev \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}