name: Django CI

on:
  push:
    branches: 
      - '**'  
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    
    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }} 
      DB_NAME: test_db
      DB_USER: root
      DB_HOST: "127.0.0.1"
      DB_PASSWORD: root
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web_editor/requirements.txt
        
    - name: Verify MySQL connection
      run: |
        sudo service mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES"
        
    - name: Create secret.json file
      uses: schdck/create-env-json@v1
      id: create-env
      with:
        file-name: 'secret.json'
        SECRET_KEY: ${{ env.SECRET_KEY }}
        DB_USER : ${{ env.DB_USER }}
        DB_PASSWORD : ${{ env.DB_PASSWORD }}
        DB_HOST: ${{ env.DB_HOST }}
        DB_NAME : ${{ env.DB_NAME }}
  
    - name: Move secret.json to correct directory
      run: |
        mv ${{ steps.create-env.outputs.full-path }} web_editor/
        
    - name: Run migrations
      run: python web_editor/manage.py migrate
    - name: Run Tests
      run: |
        python web_editor/manage.py test
